/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.captainfanatic.bites;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int current_recipe=0x7f050003;
        public static final int ingredient_checkbox=0x7f050000;
        public static final int ingredient_list=0x7f050008;
        public static final int ingredient_name=0x7f050001;
        public static final int ingredient_qty=0x7f050002;
        public static final int ingredients=0x7f050007;
        public static final int method=0x7f050009;
        public static final int method_list=0x7f05000a;
        public static final int method_step=0x7f05000b;
        public static final int recipe_list=0x7f050006;
        public static final int recipe_name=0x7f05000c;
        public static final int recipe_rating=0x7f05000d;
        public static final int recipes=0x7f050005;
        public static final int tabhost=0x7f050004;
    }
    public static final class layout {
        public static final int ingredient_row=0x7f030000;
        public static final int main=0x7f030001;
        public static final int method_row=0x7f030002;
        public static final int recipe_row=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int menu_delete=0x7f040002;
        public static final int menu_discard=0x7f040005;
        public static final int menu_insert=0x7f040003;
        public static final int menu_revert=0x7f040004;
        public static final int sql_create_table_ingredients=0x7f040007;
        public static final int sql_create_table_methods=0x7f040008;
        public static final int sql_create_table_recipes=0x7f040006;
    }
}
