/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package captainfanatic.bites;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int yellow_header=0x7f040000;
    }
    public static final class drawable {
        public static final int bites_icon=0x7f020000;
    }
    public static final class id {
        public static final int btn_Inventory=0x7f060008;
        public static final int btn_MealPlanner=0x7f06000b;
        public static final int btn_Recipes=0x7f060009;
        public static final int btn_ShoppingList=0x7f06000a;
        public static final int ingredient=0x7f060001;
        public static final int ingredientList=0x7f060011;
        public static final int method=0x7f060012;
        public static final int methodtext=0x7f060014;
        public static final int qty=0x7f060015;
        public static final int quantity=0x7f060003;
        public static final int quantitymin=0x7f060007;
        public static final int recipe=0x7f06000e;
        public static final int recipeserves=0x7f06000f;
        public static final int serves=0x7f06000d;
        public static final int step=0x7f060013;
        public static final int txt_ingredient=0x7f060000;
        public static final int txt_quantity=0x7f060002;
        public static final int txt_quantitymin=0x7f060006;
        public static final int txt_recipe=0x7f06000c;
        public static final int txt_serves=0x7f060010;
        public static final int txt_unit=0x7f060004;
        public static final int unit=0x7f060005;
    }
    public static final class layout {
        public static final int inventoryedit=0x7f030000;
        public static final int inventorylist=0x7f030001;
        public static final int inventorylist_row=0x7f030002;
        public static final int main=0x7f030003;
        public static final int mealplanneredit=0x7f030004;
        public static final int mealplannerlist=0x7f030005;
        public static final int mealplannerlist_row=0x7f030006;
        public static final int recipeedit=0x7f030007;
        public static final int recipeedit_ingredient_row=0x7f030008;
        public static final int recipeedit_ingredientlist=0x7f030009;
        public static final int recipeedit_method=0x7f03000a;
        public static final int recipeedit_method_row=0x7f03000b;
        public static final int recipeingredientadd=0x7f03000c;
        public static final int recipelist=0x7f03000d;
        public static final int recipelist_row=0x7f03000e;
        public static final int recipemake=0x7f03000f;
        public static final int recipemethodedit=0x7f030010;
        public static final int shoppinglist=0x7f030011;
        public static final int shoppinglist_row=0x7f030012;
        public static final int shoppinglistedit=0x7f030013;
    }
    public static final class string {
        public static final int app_name=0x7f05001a;
        /**  Drop table and trigger strings 
         */
        public static final int drop_t_inventory=0x7f050011;
        public static final int drop_t_mealplanner=0x7f050012;
        public static final int drop_t_recipeingredients=0x7f050013;
        public static final int drop_t_recipemethod=0x7f050014;
        public static final int drop_t_recipes=0x7f050015;
        public static final int drop_v_mealplanner=0x7f050016;
        public static final int drop_v_mealplanneringredients=0x7f050017;
        public static final int drop_v_recipeingredients=0x7f050018;
        public static final int drop_v_shoppinglist=0x7f050019;
        /**  sql table creation strings 
         */
        public static final int t_inventory_create=0x7f050000;
        public static final int t_mealplanner_create=0x7f050001;
        public static final int t_recipeingredients_create=0x7f050002;
        public static final int t_recipemethod_create=0x7f050003;
        public static final int t_recipes_create=0x7f050004;
        /**  sq trigger creation strings 
         */
        public static final int trig_t_recipes_delete=0x7f050009;
        public static final int trig_v_mealplanner_delete=0x7f05000a;
        public static final int trig_v_mealplanner_insert=0x7f05000b;
        public static final int trig_v_mealplanner_update=0x7f05000c;
        public static final int trig_v_recipeingredients_delete=0x7f05000d;
        public static final int trig_v_recipeingredients_insert=0x7f05000e;
        public static final int trig_v_recipeingredients_update=0x7f05000f;
        public static final int trig_v_shoppinglist_update=0x7f050010;
        public static final int v_mealplanner_create=0x7f050005;
        public static final int v_mealplanneringredients_create=0x7f050006;
        public static final int v_recipeingredients_create=0x7f050007;
        public static final int v_shoppinglist_create=0x7f050008;
    }
}
